version: '3'
services:
# app:
#   build:
#     context: .
#   command: ./bin/dev
#   environment:
#     PORT: 6000
#     DATABASE_URL: postgres://postgres:postgres@postgres:5432/my_project_development
#   depends_on:
#     - postgres
#   ports:
#     - '6000:6000'
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB : dogs_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '8000:5432'
